data:
  in_folder: "test_data"
  out_folder: "result"

model:
  loaded_model: "Epoch99.pth"

ROS:
  Node:
    Name: "zero_dce_enhancer"
    Topics:
      enhancing_in: "img_req_enhancer"
      enhancing_out: "img_enhanced_zeroDCE"

  Image:
    format_out: "rgb8"
